blank_issues_enabled: false
contact_links:
  - name: Support Questions
    url: https://github.com/ivancorrales/knoa/discussions/new
    about: Need support & not sure if this a bug?  You can ask questions in Slack or GitHub discussions.
